version: '3.1'
networks: 
  mynetwork:
    driver: bridge
services:
  server_api:
    build: 
      dockerfile: ./Dockerfile
      context: .
    restart: always
    ports: 
      - 3000:3000
    networks: 
      - mynetwork
    environment: 
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_VERSION=10
      - POSTGRES_URL=postgres://postgres:postgres@db/dbpost
    volumes:
      - ./:/app
    working_dir: /app
  db:
    image: postgres:10
    restart: always
    ports: 
      - 5433:5432
    environment:
      POSTGRES_DATABASE: dbpost 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks: 
      - mynetwork


      
    


    
    
      


